image: node:16

cache:
  paths:
    - node_modules/

before_script:
  - apt-get update -qq && apt-get install
  - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@6
  - pnpm config set store-dir .pnpm-store
  - pnpm prune
  - pnpm install --frozen-lockfile

stages:
  - build
  - test
  - deploy

lint-package:
  stage: build
  script:
    - pnpm lint

build-package:
  stage: build
  script:
    - pnpm build

test-package:
  stage: test
  script:
    - pnpm test
  artifacts:
    name: coverage
    paths:
      - coverage/
    expire_in: 30 days

pages:
  stage: deploy
  script:
    - pnpm publish:docs
  artifacts:
    paths:
      - public
  only:
    - master
